[package]
name = "kiorg"
version = "0.1.0"
edition = "2021"
authors = ["houqp"]
repository = "https://github.com/houqp/kiorg"

[lib]
name = "kiorg"
path = "src/lib.rs"

[[bin]]
name = "kiorg"
path = "src/main.rs"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
chrono = "0.4.40"
humansize = "2.1.3"
toml = "0.8.8"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"
dirs = "6"
open = "4.0"
clap = { version = "4.5.1", features = ["derive"] }
egui_term = { git = "https://github.com/houqp/egui_term.git", rev = "b8b4a1b79e10e07bd64d8104449e8904b466b3cd" }
notify = "8"
egui_extras = { version = "0", features = ["all_loaders"] }
zip = "2"
egui-notify = "0"
epub = "2"
file_type = "0"
egui_zhcn_fonts = "0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# image handling
image = { version = "0"}
kamadak-exif = "0"

# for pdf rendering
pdf_render = { git = "https://github.com/pdf-rs/pdf_render.git", rev = "9a31988b091495c65a54236fd6cdce8f1fa2afd0", features = ["embed"] }
pdf = { git = "https://github.com/pdf-rs/pdf" }
pathfinder_geometry = { git = "https://github.com/servo/pathfinder" }
pathfinder_export = { git = "https://github.com/servo/pathfinder" }
# pathfinder_rasterize = { git = "https://github.com/s3bk/pathfinder_rasterizer" }

[dev-dependencies]
egui_kittest = { version = "0.31.1", features = ["eframe"] }
tempfile = "3.8"

[package.metadata.bundle]
name = "Kiorg"
icon = ["assets/icon.png"]
osx_url_schemes = ["com.kiorg.kiorg"]
